version: "3.8"
services:
    web:
        image: arahbar/web
        container_name: web
        ports:
            - "80:8080"
        networks: 
            - app
        depends_on:
            - db

    db:
        image: arahbar/db
        container_name: db
        volumes:
            - ./data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - app
    cron:
        image: arahbar/cron
        container_name: cron
        depends_on: 
            - db
        networks:
            - app

networks:
    app: