version: "3.8"
services:
    web:
        build: .
        container_name: web
        ports:
            - "8080:8080"
        networks: 
            - app
    db:
        build: ./db
        container_name: db
        volumes:
            - ./db/:/etc/mysql/
            - data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: 'root'
        networks:
            - app
    cron:
        build: ./cron
        container_name: cron
        depends_on: 
            - db
        networks:
            - app

networks:
    app:
volumes:
    data: